---
title: "About this site"
description: |
  Some additional details about the website
---

This is a website (and github repository) of data and code for our work about impact of Active Case Finding on TB Case Notification in Blantyre.

We are the Helse Nord Tuberculosis Initiatve (HNTI) at Kamuzu University of Health Science and the Malawi Liverpool Wellcome Population Health group; a group of reseachers affiliated with Malawi-Liverpool-Wellcome, Liverpool School of Tropical Medicine, London School of Hygiene and Tropical Medicine, Kamuzu University of Health Sciences and University of Sheffield.

The TB electronic reporting system is a partnership between our group, Malawi National TB programme and Blantyre District Health Office.

Some more information about our research group is available at Dr Peter MacPherson's group manual here https://petermacp.github.io/mlw.public.health.group/ and the HNTI group at https://hnti.webnode.co.uk/  

We are committed to ending the HIV and TB epidemics in Malawi and globally through research, advocacy and engagement with communities.

More data about TB epidemiology in Blantyre is here https://github.com/petermacp/BlantyreTBEpi (a companion package to the paper 'MacPherson, P. et al. Disparities in access to diagnosis and care in Blantyre, Malawi, identified through enhanced tuberculosis surveillance and spatial analysis. BMC Medicine 17, 21 (2019). https://doi.org/10.1186/s12916-019-1260-6'
 )

If you have any questions, we'd be very happy to discuss.  A good first port of call is probably mnliwasa [at] kuhes [dot] ac [dot] mw or rachael.burke [at] lshtm [dot] ac [dot] uk. You can also find some of us on twitter at  [rachaelburke](https://twitter.com/rachaelburke), [petermacp](https://twitter.com/petermacp), [marriottnliwasa](https://twitter.com/marriottnliwasa) or [petedodd24](https://twitter.com/petedodd24). We love a collaboration!