---
title: "TB ACF"
description: |
  A website to share code and data from our paper about effects of ACF on TB notications in Blantyre
site: distill::distill_website
---

This website is show code to accompany the paper XXXXX.

The work is an interupted time series about the impact of Active Case Finding for TB on TB Case Notifications in Blantyre.

The github repo is at https://github.com/rachaelmburke/tbacf

To summarise:

Contents: This website has "knitted" Rmarkdown files to show our code.  Data needed is in the "mlwdata" package and in the github repo under "data_sharing" folder.

Repo: Over in the github repo you can have the unknitted .RmD files, which you should be able to use on your own computer (in the "docs" subfolder).  I have made extensive use of the "here" package, but you might find you nonetheless you will probably need to fix some relative file paths.  If you work through the four .RmD files in order and create a "data" folder locally, you should create the data you need for subsequent .rmd files.  The only thing not included here is shape files to recreate the map (the basemap is open source).

Documents:
  A Setup: Gets data from "mlwdata" package and wrangles into format needed for these analyses.
  B Tables and Figs: 
